### PR TITLE
Honours --with-libdir build option

### PR DESCRIPTION
**Pull request by remicollet**
"lib" is only the default value, can be "lib64" or anything else according to used distribution

(this may result on link error, and creating bad rpath)

### CODE REVIEW

**Comment by remicollet** [comment]
Damn process... 
PLEASE FIX THIS BUG YOURSELF.

**Comment by daschl** [comment]
@remicollet if you just sign the CLA, we (or @avsej) can get the changeset through our review system for you.

**Comment by remicollet** [comment]
IIRC, I think I already have signed it see pr #10 

BTW, I'm only a rare contributor, so I don't think it worth entering this process (which usually make possible contributor run away from such project).

I don't even use this extension, I only try to provide it to the Fedora / CentOS and RHEL users in my [repository ](https://rpms.remirepo.net/) among some other [extensions](https://blog.remirepo.net/pages/PECL-extensions-RPM-status)

I can understand why you need such a process, but really not suitable for me which works on "hundreds" different projects.

**Comment by daschl** [comment]
@remicollet that's totally okay, thanks for your contribution :) keep on sending PR's here and we'll take care of getting it in properly. Thanks again!

**Pull request closed without merging**
