### PR TITLE
PHP 7.3

### PR DESCRIPTION
**Pull request by remicollet**
1st commit is for internals changes:
see https://github.com/php/php-src/blob/master/UPGRADING.INTERNALS

2nd commit -WFormat warning nicely raised when building with 7.3 (don't know why previous don't catch these... )

### CODE REVIEW

**Comment by remicollet** [comment]
CLA already signed....

**Comment by avsej** [comment]
Thanks, @remicollet. I will import that through gerrit.

**Comment by Jan-E** [comment]
BTW: confirmed that this works in Windows as well.

**Comment by avsej** [comment]
thanks @Jan-E

**Pull request closed without merging**
